name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install glfw
      run: |
        sudo apt-get update > /dev/null && sudo apt-get -y upgrade > /dev/null
        sudo apt-get install -y libglfw3 libglfw3-dev build-essential git cmake
    - name: make
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        sudo make install
