//this is just a catch-all header
#include "ViewState.hpp"
#include "MenuBar.hpp"
#include "GuiSettings.hpp"
#include "DiffusionView.hpp"
#include "ImageView.hpp"
#include "UpscaleView.hpp"
#include "MeshView.hpp"
#include "NodeGraphView.hpp"
#include "SequencerView.hpp"
#include "CanvasView.hpp"
#include "DebugView.hpp"