#pragma once

#include "DebugView.hpp"
#include "SettingsView.hpp"
#include "WorkspaceView.hpp"
#include "PluginView.hpp"
#include "HelpView.hpp"
#include "MenuBar.hpp"
#include "project/ProjectManagerView.hpp"
#include "viewers/ImageView.hpp"
#include "viewers/VideoView.hpp"
#include "editors/ZepView.hpp"
#include "editors/NodeView.hpp"
#include "editors/ModelView.hpp"
#include "tools/SequencerView.hpp"