#pragma once

#include "DebugView.hpp"
#include "SettingsView.hpp"
#include "WorkspaceView.hpp"
#include "PluginView.hpp"
#include "HelpView.hpp"
#include "MenuBar.hpp"
#include "ProjectManagerView.hpp"
#include "ImageView.hpp"
#include "VideoView.hpp"
#include "TextEditorView.hpp"
#include "NodeView.hpp"
#include "ModelView.hpp"
#include "SequencerView.hpp"
#include "AssetsView.hpp"
#include "MediaHistoryView.hpp"
#include "MetadataView.hpp"