#pragma once

#include "DebugView.hpp"
#include "SettingsView.hpp"
#include "WorkspaceView.hpp"
#include "PluginView.hpp"
#include "HelpView.hpp"
#include "MenuBar.hpp"
#include "project/ProjectManagerView.hpp"
#include "ImageView.hpp"
#include "VideoView.hpp"
#include "ZepView.hpp"
#include "NodeView.hpp"
#include "ModelView.hpp"
#include "SequencerView.hpp"